<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b58296eb-0b21-4f66-98af-224343f1adfd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageReference Include="Azure.Core" Version="1.47.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.18" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7">
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		<PrivateAssets>all</PrivateAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
	<PackageReference Include="SparkPost" Version="2.0.2" />
	<PackageReference Include="Stripe.net" Version="48.3.0" />
	<PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />

  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Constants\" />
  </ItemGroup>

</Project>
