export type DashboardSummary = {
  totalSpentThisMonth: number;
  incomeReceivedThisMonth: number;
  totalSavings: number;
  activeBudgets: number;
  budgetAllocatedTotal: number;
  budgetSpentTotal: number;
  spendingVsLastMonthDiff: number;
  spendingIsUp: boolean;
  topSpendingCategory: string | null;
  topSpendingAmount: number;
  totalGoals: number;
  goalsNearCompletion: number;
  budgetsNearLimit: number;
  budgetsOverLimit: number;
  lowestRemainingBudgetName: string | null;
  lowestRemainingBudgetAmount: number;
  averageDailySpend: number;
  daysOverDailyAverage: number;
  upcomingExpensesCount: number;
  upcomingIncomeCount: number;
  lastIncomeAmount: number;
  lastIncomeSource: string | null;
  savingsGoalProgressPercent: number;
  nextGoalName: string | null;
  nextGoalDueDate: string | null;
  monthlyCashflowBalance: number;
  monthlyCashflowIncome: number;
  monthlyCashflowExpenses: number;
  lastUpdated: string;
  alertsCount: number;
};
