name: Deploy - Nonprod Web (Static Web App)

on:
  push:
    branches:
      - nonprod
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies with retry and mirror fallback
        run: |
          npm config set registry https://registry.npmmirror.com
          for i in 1 2 3; do
            npm install && break || sleep 10
          done
        working-directory: frontend


      - name: Build project
        run: npm run build
        working-directory: frontend

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"
          output_location: "frontend/dist"
